trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.1.0

variables:
  - group: pipeline_secrets

jobs:
  - job: Build
    displayName: Build and Save Azure Scale Set Image
    steps:
      - template: steps/azure_auth.yml@templates
        parameters:
          subscriptionId: $(TOOLING_SUBSCRIPTION_ID)
      - script: packer build .
        displayName: Packer Build
        env:
          PKR_VAR_client_id: $(AZURE_SERVICE_PRINCIPAL_ID)
          PKR_VAR_client_secret: $(AZURE_SERVICE_PRINCIPAL_SECRET)
          PKR_VAR_subscription_id: $(TOOLING_SUBSCRIPTION_ID)
          PKR_VAR_tenant_id: $(AZURE_TENANT_ID)
          PKR_VAR_tooling_resource_group_name: $(toolingResourceGroupName)
        workingDirectory: $(Build.Repository.LocalPath)/packer/azure-agents
    variables:
      toolingResourceGroupName: pins-rg-shared-tooling-uks
    workspace:
      clean: all
