trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates

variables:
  azureServiceConnection: infrastructure-tooling
  subscriptionId: edb1ff78-90da-4901-a497-7e79f966f8e2
  tooling_resource_group_name: pins-rg-shared-tooling-uks
  build_agent_scale_set_name: pins-vmss-shared-tooling-uks

stages:
  - stage: Cleanup
    displayName: Cleanup
    jobs:
      - job: Cleanup
        displayName: Delete Unused Build Agent Images
        steps:
          - task: AzurePowerShell@5
            inputs:
              ConnectedServiceNameARM: $(azureServiceConnection)
              ScriptType: 'filePath'
              ScriptPath: $(Build.Repository.LocalPath/scripts/Remove-AzVmssUnusedImages.ps1
              ScriptArguments: >
                -ResourceGroupName $(tooling_resource_group_name) `
                -VMScaleSetName $(build_agent_scale_set_name) `
                -WhatIf
              errorActionPreference: stop
              FailOnStandardError: false
              TargetAzurePs: latestVersion
            displayName: 'Cleanup Images'
