trigger: none

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
  containers:
    - container: terraform-tools
      image: terraform-tools
      endpoint: Container Registry

pool:
  vmImage: ubuntu-latest

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    deploymentStages:
      - name: Terraform Plan
        authType: terraform
        container: terraform-tools
        deploymentSteps:
          - template: ${{variables['Build.SourcesDirectory']}}/steps/terraform_plan.yml@templates
            parameters:
              subscriptionId: $(SUBSCRIPTION_ID)
              workingDirectory: $(Build.Repository.LocalPath)/infrastructure
        isDeployment: false
      - name: Terraform Apply
        authType: terraform
        container: terraform-tools
        dependsOn:
          - Terraform Plan
        deploymentSteps:
          - template: ${{variables['Build.SourcesDirectory']}}/steps/terraform_apply.yml@templates
            parameters:
              subscriptionId: $(SUBSCRIPTION_ID)
        isDeployment: true
    environments:
      - name: Tooling
    project: infrastructure
