parameters:
  - name: environments
    type: object
    default:
      - name: Tooling

trigger: none

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates

pool:
  vmImage: ubuntu-latest

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    deploymentStages:
      - name: Terraform Plan
        azureLogin: true
        deploymentSteps:
          - template: ${{variables['Build.SourcesDirectory']}}/steps/terraform_plan.yml@templates
            parameters:
              subscriptionId: $(SUBSCRIPTION_ID)
              workingDirectory: $(Build.Repository.LocalPath)/infrastructure
        isDeployment: false
      - name: Terraform Apply
        dependsOn:
          - Terraform Plan
        deploymentSteps:
          - template: ${{variables['Build.SourcesDirectory']}}/steps/terraform_apply.yml@templates
            parameters:
              subscriptionId: $(SUBSCRIPTION_ID)
        isDeployment: true
    environments: ${{ parameters.environments }}
    globalVariables:
      SUBSCRIPTION_ID: edb1ff78-90da-4901-a497-7e79f966f8e2
    project: infrastructure
