trigger: none

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/2.0.1

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    deploymentStages:
      - name: Terraform Plan
        container: terraform-tooling
        deploymentSteps:
          - template: ${{variables['Build.SourcesDirectory']}}/steps/terraform_plan.yml@templates
            parameters:
              subscriptionId: $(SUBSCRIPTION_ID)
              workingDirectory: $(Build.Repository.LocalPath)/infrastructure
        isDeployment: false
      - name: Terraform Apply
        artifact: terraform-plan
        dependsOn:
          - Terraform Plan
        deploymentSteps:
          - template: ${{variables['Build.SourcesDirectory']}}/steps/terraform_apply.yml@templates
            parameters:
              subscriptionId: $(SUBSCRIPTION_ID)
        isDeployment: true
    environments:
      - name: Tooling
    pool:
      vmImage: ubuntu-latest
