trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build_Deploy
    displayName: Build and Deploy Azure Images
    jobs:
      - job: Build_Deploy
        displayName: Build and Deploy Azure Images
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: terraform-tools
              dockerfile: pipelines/docker/terraform-tools/Dockerfile
              containerRegistry: Container Registry
              tags: latest
        workspace:
          clean: all
